import type { Product } from "../types";

export const products: Product[] = [
  {
    id: "prd-001",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Maize (Dry Corn)",
    description: "Freshly harvested dry maize from Nkwen Agro Cooperative, perfect for flour or animal feed.",
    price: 2500,
    originalPrice: 2800,
    currency: "XAF",
    category: "cereals",
    subcategory: "Maize",
    images: ["https://example.com/images/maize.jpg"],
    rating: 4.6,
    reviewCount: 132,
    stock: 120,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-08-15T09:00:00Z"),
    updatedAt: new Date("2025-02-10T11:00:00Z")
  },
  {
    id: "prd-002",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Beans (Red Kidney)",
    description: "High-quality red beans rich in protein, grown sustainably in Bamenda’s fertile soil.",
    price: 3200,
    originalPrice: 3500,
    currency: "XAF",
    category: "legumes",
    subcategory: "Beans",
    images: ["https://example.com/images/beans_red.jpg"],
    rating: 4.8,
    reviewCount: 187,
    stock: 80,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-07-25T10:30:00Z"),
    updatedAt: new Date("2025-01-20T09:00:00Z")
  },
  {
    id: "prd-003",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Irish Potatoes",
    description: "Premium Irish potatoes from the cool highlands of Santa, ideal for fries or boiling.",
    price: 2800,
    originalPrice: 3000,
    currency: "XAF",
    category: "tubers",
    subcategory: "Potatoes",
    images: ["https://example.com/images/irish_potatoes.jpg"],
    rating: 4.7,
    reviewCount: 205,
    stock: 95,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-09-05T08:45:00Z"),
    updatedAt: new Date("2025-02-15T10:00:00Z")
  },
  {
    id: "prd-004",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Cocoyams (Eddoes)",
    description: "Organic cocoyams from Ndop valley, perfect for traditional dishes and pounded meals.",
    price: 2100,
    originalPrice: 2500,
    currency: "XAF",
    category: "tubers",
    subcategory: "Cocoyams",
    images: ["https://example.com/images/cocoyams.jpg"],
    rating: 4.5,
    reviewCount: 98,
    stock: 60,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-08-02T07:50:00Z"),
    updatedAt: new Date("2025-03-01T08:00:00Z")
  },
  {
    id: "prd-005",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Yams (White Variety)",
    description: "Locally grown white yams with firm texture, freshly dug from Mbengwi farms.",
    price: 3500,
    originalPrice: 3700,
    currency: "XAF",
    category: "tubers",
    subcategory: "Yams",
    images: ["https://example.com/images/yams.jpg"],
    rating: 4.6,
    reviewCount: 144,
    stock: 88,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-10-10T09:15:00Z"),
    updatedAt: new Date("2025-02-21T09:30:00Z")
  },
  {
    id: "prd-006",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Waterleaf (Fresh)",
    description: "Freshly harvested waterleaf, rich in vitamins and ideal for soups and stews.",
    price: 600,
    originalPrice: 700,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Waterleaf",
    images: ["https://example.com/images/waterleaf.jpg"],
    rating: 4.9,
    reviewCount: 94,
    stock: 110,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-11-02T06:45:00Z"),
    updatedAt: new Date("2025-03-05T09:15:00Z")
  },
  {
    id: "prd-007",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Cabbage (Green Head)",
    description: "Crisp and healthy green cabbage grown organically in the highlands of Santa.",
    price: 900,
    originalPrice: 1000,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Cabbage",
    images: ["https://example.com/images/cabbage.jpg"],
    rating: 4.4,
    reviewCount: 78,
    stock: 75,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-07-30T09:00:00Z"),
    updatedAt: new Date("2025-02-12T11:00:00Z")
  },
  {
    id: "prd-008",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Carrots (Fresh)",
    description: "Sweet and crunchy carrots cultivated under natural conditions in Nkwen.",
    price: 850,
    originalPrice: 950,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Carrots",
    images: ["https://example.com/images/carrots.jpg"],
    rating: 4.5,
    reviewCount: 82,
    stock: 100,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-08-22T08:30:00Z"),
    updatedAt: new Date("2025-01-18T09:10:00Z")
  },
  {
    id: "prd-009",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Tomatoes (Local Variety)",
    description: "Juicy red tomatoes from Ndop Valley, ideal for sauces and salads.",
    price: 1200,
    originalPrice: 1300,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Tomatoes",
    images: ["https://example.com/images/tomatoes.jpg"],
    rating: 4.7,
    reviewCount: 167,
    stock: 95,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-06-15T07:10:00Z"),
    updatedAt: new Date("2025-02-07T10:20:00Z")
  },
  {
    id: "prd-010",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Okra (Lady Finger)",
    description: "Fresh, tender okra harvested daily from Mbengwi Fresh Fields.",
    price: 700,
    originalPrice: 800,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Okra",
    images: ["https://example.com/images/okra.jpg"],
    rating: 4.6,
    reviewCount: 109,
    stock: 90,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-09-09T08:00:00Z"),
    updatedAt: new Date("2025-02-19T09:30:00Z")
  },
    {
    id: "prd-011",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Spinach (Green)",
    description: "Fresh green spinach, rich in iron and vitamins, harvested from the cool hills of Santa.",
    price: 800,
    originalPrice: 900,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Spinach",
    images: ["https://example.com/images/spinach.jpg"],
    rating: 4.8,
    reviewCount: 102,
    stock: 70,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-07-11T07:00:00Z"),
    updatedAt: new Date("2025-02-20T09:45:00Z")
  },
  {
    id: "prd-012",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Pepper (Red Hot)",
    description: "Locally grown hot red pepper, ideal for spicing up traditional Cameroonian dishes.",
    price: 1000,
    originalPrice: 1100,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Pepper",
    images: ["https://example.com/images/pepper.jpg"],
    rating: 4.5,
    reviewCount: 150,
    stock: 95,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-08-10T09:20:00Z"),
    updatedAt: new Date("2025-01-28T08:30:00Z")
  },
  {
    id: "prd-013",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Cassava (Tubers)",
    description: "High-yield cassava tubers, suitable for garri, fufu, and other local delicacies.",
    price: 2400,
    originalPrice: 2700,
    currency: "XAF",
    category: "tubers",
    subcategory: "Cassava",
    images: ["https://example.com/images/cassava.jpg"],
    rating: 4.6,
    reviewCount: 128,
    stock: 82,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-07-28T06:40:00Z"),
    updatedAt: new Date("2025-02-18T10:00:00Z")
  },
  {
    id: "prd-014",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Bananas (Ripe)",
    description: "Sweet, naturally ripened bananas grown on the fertile hillsides of Bamenda.",
    price: 1200,
    originalPrice: 1300,
    currency: "XAF",
    category: "fruits",
    subcategory: "Bananas",
    images: ["https://example.com/images/bananas.jpg"],
    rating: 4.7,
    reviewCount: 190,
    stock: 120,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-09-14T08:10:00Z"),
    updatedAt: new Date("2025-02-14T09:30:00Z")
  },
  {
    id: "prd-015",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Oranges (Sweet)",
    description: "Juicy and sweet oranges harvested from Mbengwi’s sunny orchards.",
    price: 1500,
    originalPrice: 1600,
    currency: "XAF",
    category: "fruits",
    subcategory: "Oranges",
    images: ["https://example.com/images/oranges.jpg"],
    rating: 4.9,
    reviewCount: 220,
    stock: 85,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-08-25T07:50:00Z"),
    updatedAt: new Date("2025-03-01T09:15:00Z")
  },
  {
    id: "prd-016",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Groundnuts (Shelled)",
    description: "Freshly harvested and dried groundnuts from Nkwen Agro Cooperative.",
    price: 2800,
    originalPrice: 3000,
    currency: "XAF",
    category: "legumes",
    subcategory: "Groundnuts",
    images: ["https://example.com/images/groundnuts.jpg"],
    rating: 4.6,
    reviewCount: 134,
    stock: 75,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-10-11T09:00:00Z"),
    updatedAt: new Date("2025-02-11T08:45:00Z")
  },
  {
    id: "prd-017",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Millet (Grains)",
    description: "Locally grown millet, perfect for traditional pap and local beer brewing.",
    price: 2700,
    originalPrice: 2900,
    currency: "XAF",
    category: "cereals",
    subcategory: "Millet",
    images: ["https://example.com/images/millet.jpg"],
    rating: 4.4,
    reviewCount: 90,
    stock: 60,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-07-21T08:20:00Z"),
    updatedAt: new Date("2025-01-23T09:10:00Z")
  },
  {
    id: "prd-018",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Cocoa Beans",
    description: "Premium grade cocoa beans, naturally fermented and sun-dried from Ndop Valley.",
    price: 4800,
    originalPrice: 5000,
    currency: "XAF",
    category: "cashCrops",
    subcategory: "Cocoa",
    images: ["https://example.com/images/cocoa_beans.jpg"],
    rating: 4.8,
    reviewCount: 244,
    stock: 45,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-06-18T09:15:00Z"),
    updatedAt: new Date("2025-02-22T08:30:00Z")
  },
  {
    id: "prd-019",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Coffee Beans (Robusta)",
    description: "Aromatic Robusta coffee beans grown in the highlands around Mbengwi.",
    price: 4200,
    originalPrice: 4500,
    currency: "XAF",
    category: "cashCrops",
    subcategory: "Coffee",
    images: ["https://example.com/images/coffee_beans.jpg"],
    rating: 4.9,
    reviewCount: 312,
    stock: 55,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-07-30T09:50:00Z"),
    updatedAt: new Date("2025-03-04T09:00:00Z")
  },
  {
    id: "prd-020",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Palm Nuts (Oil Palm Fruit)",
    description: "Rich and fresh palm nuts used for red palm oil production, harvested from Bamenda Green Farms.",
    price: 2600,
    originalPrice: 2800,
    currency: "XAF",
    category: "cashCrops",
    subcategory: "Palm Nuts",
    images: ["https://example.com/images/palm_nuts.jpg"],
    rating: 4.5,
    reviewCount: 141,
    stock: 78,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-09-17T09:10:00Z"),
    updatedAt: new Date("2025-02-25T08:50:00Z")
  },

    {
    id: "prd-021",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Tomatoes (Cherry)",
    description: "Small and sweet cherry tomatoes, perfect for salads and garnishing.",
    price: 1300,
    originalPrice: 1500,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Tomatoes",
    images: ["https://example.com/images/cherry_tomatoes.jpg"],
    rating: 4.7,
    reviewCount: 88,
    stock: 95,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-08-05T08:20:00Z"),
    updatedAt: new Date("2025-01-30T09:10:00Z")
  },
  {
    id: "prd-022",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Cabbage (Red)",
    description: "Crisp red cabbage, grown organically in the fertile Santa highlands.",
    price: 950,
    originalPrice: 1100,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Cabbage",
    images: ["https://example.com/images/red_cabbage.jpg"],
    rating: 4.5,
    reviewCount: 72,
    stock: 80,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-09-01T07:45:00Z"),
    updatedAt: new Date("2025-02-12T10:00:00Z")
  },
  {
    id: "prd-023",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Green Peppers",
    description: "Fresh green bell peppers, ideal for stews and local sauces.",
    price: 1100,
    originalPrice: 1200,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Peppers",
    images: ["https://example.com/images/green_peppers.jpg"],
    rating: 4.6,
    reviewCount: 94,
    stock: 100,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-08-20T09:00:00Z"),
    updatedAt: new Date("2025-02-22T09:15:00Z")
  },
  {
    id: "prd-024",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Waterleaf (Dried)",
    description: "Sun-dried waterleaf, ready for long-term storage and soups.",
    price: 700,
    originalPrice: 800,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Waterleaf",
    images: ["https://example.com/images/dried_waterleaf.jpg"],
    rating: 4.8,
    reviewCount: 65,
    stock: 120,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-07-15T08:30:00Z"),
    updatedAt: new Date("2025-02-18T09:00:00Z")
  },
  {
    id: "prd-025",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Irish Potatoes (Small)",
    description: "Small but flavorful Irish potatoes, perfect for stews and side dishes.",
    price: 2600,
    originalPrice: 2800,
    currency: "XAF",
    category: "tubers",
    subcategory: "Potatoes",
    images: ["https://example.com/images/irish_potatoes_small.jpg"],
    rating: 4.6,
    reviewCount: 112,
    stock: 75,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-09-10T07:50:00Z"),
    updatedAt: new Date("2025-02-20T08:30:00Z")
  },
  {
    id: "prd-026",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Yams (Purple Variety)",
    description: "Organic purple yams, traditionally grown and harvested from Nkwen farms.",
    price: 3700,
    originalPrice: 4000,
    currency: "XAF",
    category: "tubers",
    subcategory: "Yams",
    images: ["https://example.com/images/purple_yams.jpg"],
    rating: 4.7,
    reviewCount: 120,
    stock: 60,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-10-05T09:10:00Z"),
    updatedAt: new Date("2025-02-28T09:45:00Z")
  },
  {
    id: "prd-027",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Bitterleaf (Fresh)",
    description: "Freshly harvested bitterleaf, ideal for traditional Cameroonian soups.",
    price: 750,
    originalPrice: 850,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Bitterleaf",
    images: ["https://example.com/images/bitterleaf.jpg"],
    rating: 4.9,
    reviewCount: 58,
    stock: 100,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-07-28T08:15:00Z"),
    updatedAt: new Date("2025-02-17T09:00:00Z")
  },
  {
    id: "prd-028",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Bananas (Plantain)",
    description: "Green plantains from Mbengwi farms, perfect for frying and boiling.",
    price: 1000,
    originalPrice: 1100,
    currency: "XAF",
    category: "fruits",
    subcategory: "Plantains",
    images: ["https://example.com/images/plantains.jpg"],
    rating: 4.7,
    reviewCount: 140,
    stock: 110,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-08-15T08:00:00Z"),
    updatedAt: new Date("2025-02-25T09:30:00Z")
  },
  {
    id: "prd-029",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Citrus (Limes)",
    description: "Fresh green limes, bursting with juice and flavor, from Bamenda.",
    price: 900,
    originalPrice: 1000,
    currency: "XAF",
    category: "fruits",
    subcategory: "Citrus",
    images: ["https://example.com/images/limes.jpg"],
    rating: 4.8,
    reviewCount: 110,
    stock: 120,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-09-01T09:00:00Z"),
    updatedAt: new Date("2025-02-20T09:15:00Z")
  },
  {
    id: "prd-030",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Avocado (Green)",
    description: "Creamy green avocados, harvested from Ndop Valley, ideal for local dishes and salads.",
    price: 1800,
    originalPrice: 2000,
    currency: "XAF",
    category: "fruits",
    subcategory: "Avocado",
    images: ["https://example.com/images/avocado.jpg"],
    rating: 4.7,
    reviewCount: 95,
    stock: 85,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-08-12T07:50:00Z"),
    updatedAt: new Date("2025-02-28T08:45:00Z")
  },

    {
    id: "prd-031",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Maize (White)",
    description: "Freshly harvested white maize, perfect for porridge, fufu, and local dishes.",
    price: 2200,
    originalPrice: 2400,
    currency: "XAF",
    category: "grains",
    subcategory: "Maize",
    images: ["https://example.com/images/white_maize.jpg"],
    rating: 4.8,
    reviewCount: 140,
    stock: 90,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-07-20T08:00:00Z"),
    updatedAt: new Date("2025-02-15T09:20:00Z")
  },
  {
    id: "prd-032",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Beans (Red Kidney)",
    description: "Nutritious red kidney beans, grown organically in Santa highlands.",
    price: 2500,
    originalPrice: 2700,
    currency: "XAF",
    category: "grains",
    subcategory: "Beans",
    images: ["https://example.com/images/red_kidney_beans.jpg"],
    rating: 4.9,
    reviewCount: 120,
    stock: 80,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-08-10T08:30:00Z"),
    updatedAt: new Date("2025-02-18T09:00:00Z")
  },
  {
    id: "prd-033",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Soybeans",
    description: "Locally grown soybeans, ideal for soups, sauces, and snacks.",
    price: 2800,
    originalPrice: 3000,
    currency: "XAF",
    category: "grains",
    subcategory: "Beans",
    images: ["https://example.com/images/soybeans.jpg"],
    rating: 4.7,
    reviewCount: 95,
    stock: 70,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-09-01T09:00:00Z"),
    updatedAt: new Date("2025-02-22T09:15:00Z")
  },
  {
    id: "prd-034",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Groundnuts (Raw)",
    description: "Freshly harvested groundnuts, perfect for roasting or making local sauces.",
    price: 2600,
    originalPrice: 2800,
    currency: "XAF",
    category: "grains",
    subcategory: "Groundnuts",
    images: ["https://example.com/images/raw_groundnuts.jpg"],
    rating: 4.6,
    reviewCount: 105,
    stock: 85,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-07-28T08:20:00Z"),
    updatedAt: new Date("2025-02-19T09:00:00Z")
  },
  {
    id: "prd-035",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Millet (Local)",
    description: "Locally grown millet for porridge and traditional brewing.",
    price: 2300,
    originalPrice: 2500,
    currency: "XAF",
    category: "grains",
    subcategory: "Grains",
    images: ["https://example.com/images/millet_local.jpg"],
    rating: 4.5,
    reviewCount: 88,
    stock: 90,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-08-15T08:45:00Z"),
    updatedAt: new Date("2025-02-20T09:10:00Z")
  },
  {
    id: "prd-036",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Yams (White)",
    description: "Freshly harvested white yams, ideal for boiling and traditional dishes.",
    price: 3800,
    originalPrice: 4000,
    currency: "XAF",
    category: "tubers",
    subcategory: "Yams",
    images: ["https://example.com/images/white_yams.jpg"],
    rating: 4.8,
    reviewCount: 115,
    stock: 70,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-10-05T09:10:00Z"),
    updatedAt: new Date("2025-03-01T09:40:00Z")
  },
  {
    id: "prd-037",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Cucumbers (Fresh)",
    description: "Fresh and crisp cucumbers, perfect for salads and local meals.",
    price: 900,
    originalPrice: 1000,
    currency: "XAF",
    category: "vegetables",
    subcategory: "Cucumbers",
    images: ["https://example.com/images/cucumbers.jpg"],
    rating: 4.6,
    reviewCount: 65,
    stock: 100,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-07-18T08:30:00Z"),
    updatedAt: new Date("2025-02-17T09:00:00Z")
  },
  {
    id: "prd-038",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Basil (Fresh)",
    description: "Aromatic fresh basil leaves, perfect for soups, stews, and garnishing.",
    price: 600,
    originalPrice: 700,
    currency: "XAF",
    category: "herbs",
    subcategory: "Basil",
    images: ["https://example.com/images/basil.jpg"],
    rating: 4.7,
    reviewCount: 52,
    stock: 120,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-08-01T07:50:00Z"),
    updatedAt: new Date("2025-02-20T08:30:00Z")
  },
  {
    id: "prd-039",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Mint (Fresh)",
    description: "Freshly harvested mint leaves, ideal for teas and garnishes.",
    price: 650,
    originalPrice: 750,
    currency: "XAF",
    category: "herbs",
    subcategory: "Mint",
    images: ["https://example.com/images/mint.jpg"],
    rating: 4.8,
    reviewCount: 60,
    stock: 100,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-08-12T08:00:00Z"),
    updatedAt: new Date("2025-02-22T09:10:00Z")
  },
  {
    id: "prd-040",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Parsley (Fresh)",
    description: "Fresh parsley leaves, grown organically, perfect for local dishes and soups.",
    price: 700,
    originalPrice: 800,
    currency: "XAF",
    category: "herbs",
    subcategory: "Parsley",
    images: ["https://example.com/images/parsley.jpg"],
    rating: 4.7,
    reviewCount: 55,
    stock: 110,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-07-22T08:10:00Z"),
    updatedAt: new Date("2025-02-18T08:50:00Z")
  },

    {
    id: "prd-041",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Cilantro (Fresh)",
    description: "Fresh cilantro leaves, perfect for sauces, soups, and garnishing.",
    price: 650,
    originalPrice: 750,
    currency: "XAF",
    category: "herbs",
    subcategory: "Cilantro",
    images: ["https://example.com/images/cilantro.jpg"],
    rating: 4.8,
    reviewCount: 50,
    stock: 100,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-08-05T08:20:00Z"),
    updatedAt: new Date("2025-02-25T09:10:00Z")
  },
  {
    id: "prd-042",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Cheese (Local)",
    description: "Freshly produced local cheese from Santa Highlands, perfect for snacks and cooking.",
    price: 3200,
    originalPrice: 3500,
    currency: "XAF",
    category: "dairy",
    subcategory: "Cheese",
    images: ["https://example.com/images/local_cheese.jpg"],
    rating: 4.7,
    reviewCount: 68,
    stock: 60,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-09-01T08:40:00Z"),
    updatedAt: new Date("2025-02-20T09:20:00Z")
  },
  {
    id: "prd-043",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Yogurt (Plain)",
    description: "Natural plain yogurt made from local milk, fresh and creamy.",
    price: 1800,
    originalPrice: 2000,
    currency: "XAF",
    category: "dairy",
    subcategory: "Yogurt",
    images: ["https://example.com/images/plain_yogurt.jpg"],
    rating: 4.6,
    reviewCount: 55,
    stock: 75,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-08-12T08:50:00Z"),
    updatedAt: new Date("2025-02-22T09:00:00Z")
  },
  {
    id: "prd-044",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Milk (Fresh)",
    description: "Fresh cow milk directly from Mbengwi farms, perfect for drinking and cooking.",
    price: 1500,
    originalPrice: 1700,
    currency: "XAF",
    category: "dairy",
    subcategory: "Milk",
    images: ["https://example.com/images/fresh_milk.jpg"],
    rating: 4.8,
    reviewCount: 70,
    stock: 90,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-07-28T08:10:00Z"),
    updatedAt: new Date("2025-02-18T09:00:00Z")
  },
  {
    id: "prd-045",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Butter (Local)",
    description: "Creamy local butter, perfect for cooking or spreading on bread.",
    price: 2800,
    originalPrice: 3000,
    currency: "XAF",
    category: "dairy",
    subcategory: "Butter",
    images: ["https://example.com/images/local_butter.jpg"],
    rating: 4.7,
    reviewCount: 60,
    stock: 65,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-08-15T08:20:00Z"),
    updatedAt: new Date("2025-02-20T09:10:00Z")
  },
  {
    id: "prd-046",
    farmerId: "F001",
    farmerName: "Nkwen Agro Cooperative",
    name: "Papaya (Ripe)",
    description: "Sweet and juicy ripe papayas, locally grown in Nkwen.",
    price: 1500,
    originalPrice: 1700,
    currency: "XAF",
    category: "fruits",
    subcategory: "Tropical",
    images: ["https://example.com/images/ripe_papaya.jpg"],
    rating: 4.9,
    reviewCount: 85,
    stock: 80,
    isAvailable: true,
    location: "Nkwen",
    createdAt: new Date("2024-09-05T07:50:00Z"),
    updatedAt: new Date("2025-02-25T08:30:00Z")
  },
  {
    id: "prd-047",
    farmerId: "F003",
    farmerName: "Santa Highlands Produce",
    name: "Pineapple (Sweet)",
    description: "Juicy and sweet pineapples, perfect for fresh consumption or juice.",
    price: 2000,
    originalPrice: 2200,
    currency: "XAF",
    category: "fruits",
    subcategory: "Tropical",
    images: ["https://example.com/images/sweet_pineapple.jpg"],
    rating: 4.8,
    reviewCount: 90,
    stock: 70,
    isAvailable: true,
    location: "Santa",
    createdAt: new Date("2024-08-10T08:00:00Z"),
    updatedAt: new Date("2025-02-22T09:10:00Z")
  },
  {
    id: "prd-048",
    farmerId: "F004",
    farmerName: "Ndop Valley Growers",
    name: "Strawberries (Fresh)",
    description: "Freshly picked strawberries, sweet and tangy, from Ndop Valley.",
    price: 2500,
    originalPrice: 2800,
    currency: "XAF",
    category: "fruits",
    subcategory: "Berries",
    images: ["https://example.com/images/fresh_strawberries.jpg"],
    rating: 4.9,
    reviewCount: 78,
    stock: 60,
    isAvailable: true,
    location: "Ndop",
    createdAt: new Date("2024-08-20T08:30:00Z"),
    updatedAt: new Date("2025-02-25T09:15:00Z")
  },
  {
    id: "prd-049",
    farmerId: "F005",
    farmerName: "Mbengwi Fresh Fields",
    name: "Bananas (Ripe)",
    description: "Sweet ripe bananas from Mbengwi, ideal for eating or cooking.",
    price: 1200,
    originalPrice: 1400,
    currency: "XAF",
    category: "fruits",
    subcategory: "Tropical",
    images: ["https://example.com/images/ripe_bananas.jpg"],
    rating: 4.7,
    reviewCount: 95,
    stock: 90,
    isAvailable: true,
    location: "Mbengwi",
    createdAt: new Date("2024-08-18T07:45:00Z"),
    updatedAt: new Date("2025-02-22T09:00:00Z")
  },
  {
    id: "prd-050",
    farmerId: "F002",
    farmerName: "Bamenda Green Farms",
    name: "Oranges (Juicy)",
    description: "Juicy oranges, locally grown in Bamenda, perfect for juice or eating fresh.",
    price: 1600,
    originalPrice: 1800,
    currency: "XAF",
    category: "fruits",
    subcategory: "Citrus",
    images: ["https://example.com/images/juicy_oranges.jpg"],
    rating: 4.8,
    reviewCount: 80,
    stock: 85,
    isAvailable: true,
    location: "Bamenda",
    createdAt: new Date("2024-08-12T08:10:00Z"),
    updatedAt: new Date("2025-02-20T09:05:00Z")
  },

];